# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.srcs/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_cnn_top_0_0/ZYNQ_CORE_cnn_top_0_0.xci
# IP: The module: 'ZYNQ_CORE_cnn_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# IP: D:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# IP: D:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.srcs/sources_1/ip/rom_w4_ip/rom_w4_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom_w4_ip || ORIG_REF_NAME==rom_w4_ip} -quiet] -quiet

# IP: D:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.srcs/sources_1/ip/rom_w3_ip/rom_w3_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom_w3_ip || ORIG_REF_NAME==rom_w3_ip} -quiet] -quiet

# IP: D:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.srcs/sources_1/ip/rom_w2_ip/rom_w2_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom_w2_ip || ORIG_REF_NAME==rom_w2_ip} -quiet] -quiet

# IP: D:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.srcs/sources_1/ip/rom_w1_ip/rom_w1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom_w1_ip || ORIG_REF_NAME==rom_w1_ip} -quiet] -quiet

# IP: D:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.srcs/sources_1/ip/rom_w0_ip/rom_w0_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom_w0_ip || ORIG_REF_NAME==rom_w0_ip} -quiet] -quiet

# IP: D:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.srcs/sources_1/ip/rom_b_ip/rom_b_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom_b_ip || ORIG_REF_NAME==rom_b_ip} -quiet] -quiet

# IP: D:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.srcs/sources_1/ip/data_ram_ip/data_ram_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_ram_ip || ORIG_REF_NAME==data_ram_ip} -quiet] -quiet

# XDC: d:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.gen/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.gen/sources_1/ip/rom_w4_ip/rom_w4_ip_ooc.xdc

# XDC: d:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.gen/sources_1/ip/rom_w3_ip/rom_w3_ip_ooc.xdc

# XDC: d:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.gen/sources_1/ip/rom_w2_ip/rom_w2_ip_ooc.xdc

# XDC: d:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.gen/sources_1/ip/rom_w1_ip/rom_w1_ip_ooc.xdc

# XDC: d:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.gen/sources_1/ip/rom_w0_ip/rom_w0_ip_ooc.xdc

# XDC: d:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.gen/sources_1/ip/rom_b_ip/rom_b_ip_ooc.xdc

# XDC: d:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.gen/sources_1/ip/data_ram_ip/data_ram_ip_ooc.xdc

# IP: D:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.srcs/sources_1/bd/ZYNQ_CORE/ip/ZYNQ_CORE_cnn_top_0_0/ZYNQ_CORE_cnn_top_0_0.xci
# IP: The module: 'ZYNQ_CORE_cnn_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# IP: D:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# IP: D:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.srcs/sources_1/ip/rom_w4_ip/rom_w4_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom_w4_ip || ORIG_REF_NAME==rom_w4_ip} -quiet] -quiet

# IP: D:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.srcs/sources_1/ip/rom_w3_ip/rom_w3_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom_w3_ip || ORIG_REF_NAME==rom_w3_ip} -quiet] -quiet

# IP: D:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.srcs/sources_1/ip/rom_w2_ip/rom_w2_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom_w2_ip || ORIG_REF_NAME==rom_w2_ip} -quiet] -quiet

# IP: D:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.srcs/sources_1/ip/rom_w1_ip/rom_w1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom_w1_ip || ORIG_REF_NAME==rom_w1_ip} -quiet] -quiet

# IP: D:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.srcs/sources_1/ip/rom_w0_ip/rom_w0_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom_w0_ip || ORIG_REF_NAME==rom_w0_ip} -quiet] -quiet

# IP: D:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.srcs/sources_1/ip/rom_b_ip/rom_b_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom_b_ip || ORIG_REF_NAME==rom_b_ip} -quiet] -quiet

# IP: D:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.srcs/sources_1/ip/data_ram_ip/data_ram_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_ram_ip || ORIG_REF_NAME==data_ram_ip} -quiet] -quiet

# XDC: d:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.gen/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.gen/sources_1/ip/rom_w4_ip/rom_w4_ip_ooc.xdc

# XDC: d:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.gen/sources_1/ip/rom_w3_ip/rom_w3_ip_ooc.xdc

# XDC: d:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.gen/sources_1/ip/rom_w2_ip/rom_w2_ip_ooc.xdc

# XDC: d:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.gen/sources_1/ip/rom_w1_ip/rom_w1_ip_ooc.xdc

# XDC: d:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.gen/sources_1/ip/rom_w0_ip/rom_w0_ip_ooc.xdc

# XDC: d:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.gen/sources_1/ip/rom_b_ip/rom_b_ip_ooc.xdc

# XDC: d:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.gen/sources_1/ip/data_ram_ip/data_ram_ip_ooc.xdc
