# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/OV.xdc

# IP: ip/fifo_generator_0/fifo_generator_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# IP: ip/mult_gen_0/mult_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# IP: ip/rom_w4_ip/rom_w4_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom_w4_ip || ORIG_REF_NAME==rom_w4_ip} -quiet] -quiet

# IP: ip/rom_w3_ip/rom_w3_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom_w3_ip || ORIG_REF_NAME==rom_w3_ip} -quiet] -quiet

# IP: ip/rom_w2_ip/rom_w2_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom_w2_ip || ORIG_REF_NAME==rom_w2_ip} -quiet] -quiet

# IP: ip/rom_w1_ip/rom_w1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom_w1_ip || ORIG_REF_NAME==rom_w1_ip} -quiet] -quiet

# IP: ip/rom_w0_ip/rom_w0_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom_w0_ip || ORIG_REF_NAME==rom_w0_ip} -quiet] -quiet

# IP: ip/rom_b_ip/rom_b_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom_b_ip || ORIG_REF_NAME==rom_b_ip} -quiet] -quiet

# IP: ip/data_ram_ip/data_ram_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_ram_ip || ORIG_REF_NAME==data_ram_ip} -quiet] -quiet

# Block Designs: bd/ZYNQ_CORE/ZYNQ_CORE.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE || ORIG_REF_NAME==ZYNQ_CORE} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_processing_system7_0_0/ZYNQ_CORE_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_processing_system7_0_0 || ORIG_REF_NAME==ZYNQ_CORE_processing_system7_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_vdma_0_0/ZYNQ_CORE_axi_vdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_axi_vdma_0_0 || ORIG_REF_NAME==ZYNQ_CORE_axi_vdma_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_v_axi4s_vid_out_0_0/ZYNQ_CORE_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==ZYNQ_CORE_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_v_tc_0_0/ZYNQ_CORE_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_v_tc_0_0 || ORIG_REF_NAME==ZYNQ_CORE_v_tc_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_clk_wiz_0_0/ZYNQ_CORE_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_clk_wiz_0_0 || ORIG_REF_NAME==ZYNQ_CORE_clk_wiz_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_xbar_1/ZYNQ_CORE_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_xbar_1 || ORIG_REF_NAME==ZYNQ_CORE_xbar_1} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_ps7_0_axi_periph_1/ZYNQ_CORE_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_ps7_0_axi_periph_1 || ORIG_REF_NAME==ZYNQ_CORE_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_rst_ps7_0_50M_1/ZYNQ_CORE_rst_ps7_0_50M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_rst_ps7_0_50M_1 || ORIG_REF_NAME==ZYNQ_CORE_rst_ps7_0_50M_1} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_xbar_0/ZYNQ_CORE_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_xbar_0 || ORIG_REF_NAME==ZYNQ_CORE_xbar_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_mem_intercon_1/ZYNQ_CORE_axi_mem_intercon_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_axi_mem_intercon_1 || ORIG_REF_NAME==ZYNQ_CORE_axi_mem_intercon_1} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_rst_ps7_0_150M_1/ZYNQ_CORE_rst_ps7_0_150M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_rst_ps7_0_150M_1 || ORIG_REF_NAME==ZYNQ_CORE_rst_ps7_0_150M_1} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_util_vector_logic_0_0/ZYNQ_CORE_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_util_vector_logic_0_0 || ORIG_REF_NAME==ZYNQ_CORE_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_rgb2dvi_0_0/ZYNQ_CORE_rgb2dvi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_rgb2dvi_0_0 || ORIG_REF_NAME==ZYNQ_CORE_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_v_vid_in_axi4s_0_0/ZYNQ_CORE_v_vid_in_axi4s_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==ZYNQ_CORE_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_ov5640_capture_data_0_0/ZYNQ_CORE_ov5640_capture_data_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_ov5640_capture_data_0_0 || ORIG_REF_NAME==ZYNQ_CORE_ov5640_capture_data_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_blk_mem_gen_0_0/ZYNQ_CORE_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_blk_mem_gen_0_0 || ORIG_REF_NAME==ZYNQ_CORE_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_show_num_0_1/ZYNQ_CORE_show_num_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_show_num_0_1 || ORIG_REF_NAME==ZYNQ_CORE_show_num_0_1} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_cycle_num_0_1/ZYNQ_CORE_cycle_num_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_cycle_num_0_1 || ORIG_REF_NAME==ZYNQ_CORE_cycle_num_0_1} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_xlconstant_1_0/ZYNQ_CORE_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_xlconstant_1_0 || ORIG_REF_NAME==ZYNQ_CORE_xlconstant_1_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_border_adder_0_0/ZYNQ_CORE_border_adder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_border_adder_0_0 || ORIG_REF_NAME==ZYNQ_CORE_border_adder_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_binarizer_0_0/ZYNQ_CORE_binarizer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_binarizer_0_0 || ORIG_REF_NAME==ZYNQ_CORE_binarizer_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_blk_mem_gen_1_1/ZYNQ_CORE_blk_mem_gen_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_blk_mem_gen_1_1 || ORIG_REF_NAME==ZYNQ_CORE_blk_mem_gen_1_1} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_cnn_top_0_0/ZYNQ_CORE_cnn_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_cnn_top_0_0 || ORIG_REF_NAME==ZYNQ_CORE_cnn_top_0_0} -quiet] -quiet

# IP: ip/fifo_generator_0/fifo_generator_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# IP: ip/mult_gen_0/mult_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# IP: ip/rom_w4_ip/rom_w4_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom_w4_ip || ORIG_REF_NAME==rom_w4_ip} -quiet] -quiet

# IP: ip/rom_w3_ip/rom_w3_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom_w3_ip || ORIG_REF_NAME==rom_w3_ip} -quiet] -quiet

# IP: ip/rom_w2_ip/rom_w2_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom_w2_ip || ORIG_REF_NAME==rom_w2_ip} -quiet] -quiet

# IP: ip/rom_w1_ip/rom_w1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom_w1_ip || ORIG_REF_NAME==rom_w1_ip} -quiet] -quiet

# IP: ip/rom_w0_ip/rom_w0_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom_w0_ip || ORIG_REF_NAME==rom_w0_ip} -quiet] -quiet

# IP: ip/rom_b_ip/rom_b_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rom_b_ip || ORIG_REF_NAME==rom_b_ip} -quiet] -quiet

# IP: ip/data_ram_ip/data_ram_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_ram_ip || ORIG_REF_NAME==data_ram_ip} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_bram_ctrl_0_0/ZYNQ_CORE_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_axi_bram_ctrl_0_0 || ORIG_REF_NAME==ZYNQ_CORE_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_xlslice_0_0/ZYNQ_CORE_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_xlslice_0_0 || ORIG_REF_NAME==ZYNQ_CORE_xlslice_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_bram_wr_ctrl_0_0/ZYNQ_CORE_bram_wr_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_bram_wr_ctrl_0_0 || ORIG_REF_NAME==ZYNQ_CORE_bram_wr_ctrl_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_xlconstant_0_0/ZYNQ_CORE_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_xlconstant_0_0 || ORIG_REF_NAME==ZYNQ_CORE_xlconstant_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_axi_gpio_0_0/ZYNQ_CORE_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_axi_gpio_0_0 || ORIG_REF_NAME==ZYNQ_CORE_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_auto_pc_3/ZYNQ_CORE_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_auto_pc_3 || ORIG_REF_NAME==ZYNQ_CORE_auto_pc_3} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_auto_pc_0/ZYNQ_CORE_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_auto_pc_0 || ORIG_REF_NAME==ZYNQ_CORE_auto_pc_0} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_auto_pc_1/ZYNQ_CORE_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_auto_pc_1 || ORIG_REF_NAME==ZYNQ_CORE_auto_pc_1} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_auto_pc_2/ZYNQ_CORE_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_auto_pc_2 || ORIG_REF_NAME==ZYNQ_CORE_auto_pc_2} -quiet] -quiet

# IP: bd/ZYNQ_CORE/ip/ZYNQ_CORE_auto_pc_4/ZYNQ_CORE_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_CORE_auto_pc_4 || ORIG_REF_NAME==ZYNQ_CORE_auto_pc_4} -quiet] -quiet

# XDC: d:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.gen/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.gen/sources_1/ip/rom_w4_ip/rom_w4_ip_ooc.xdc

# XDC: d:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.gen/sources_1/ip/rom_w3_ip/rom_w3_ip_ooc.xdc

# XDC: d:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.gen/sources_1/ip/rom_w2_ip/rom_w2_ip_ooc.xdc

# XDC: d:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.gen/sources_1/ip/rom_w1_ip/rom_w1_ip_ooc.xdc

# XDC: d:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.gen/sources_1/ip/rom_w0_ip/rom_w0_ip_ooc.xdc

# XDC: d:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.gen/sources_1/ip/rom_b_ip/rom_b_ip_ooc.xdc

# XDC: d:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.gen/sources_1/ip/data_ram_ip/data_ram_ip_ooc.xdc

# XDC: d:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.gen/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.gen/sources_1/ip/rom_w4_ip/rom_w4_ip_ooc.xdc

# XDC: d:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.gen/sources_1/ip/rom_w3_ip/rom_w3_ip_ooc.xdc

# XDC: d:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.gen/sources_1/ip/rom_w2_ip/rom_w2_ip_ooc.xdc

# XDC: d:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.gen/sources_1/ip/rom_w1_ip/rom_w1_ip_ooc.xdc

# XDC: d:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.gen/sources_1/ip/rom_w0_ip/rom_w0_ip_ooc.xdc

# XDC: d:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.gen/sources_1/ip/rom_b_ip/rom_b_ip_ooc.xdc

# XDC: d:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.gen/sources_1/ip/data_ram_ip/data_ram_ip_ooc.xdc

# XDC: d:/Programs/Workspace/Xilinx_Prj/PL_CNN/PL_CNN.gen/sources_1/bd/ZYNQ_CORE/ZYNQ_CORE_ooc.xdc
